name: Deployment
on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  docker_image_tag: ${{ github.ref == 'refs/heads/main' && github.sha || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - uses: integration-os/google-artifact-registry-action@v1
        with:
          image: "us-east4-docker.pkg.dev/buildable-production/event-docker/oauth:${{ env.docker_image_tag }}"
          build-args: "CARGO_REGISTRIES_CLOUDSMITH_TOKEN=${{ secrets.CLOUDSMITH_API_KEY }}"

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: integration-os/development-environment-deploy-action@v1
        with:
          ssh_key: ${{ secrets.INFRASTRUCTURE_DEPLOY_KEY }}
          service_name: oauth-api
          yaml_path: .event.services.oauthApi.image.tag
          docker_image_tag: ${{ env.docker_image_tag }}
